src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use \DateTime;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $content;

    /**
     * @ORM\Column(type="date")
     * @Assert\Type("\DateTime")
     */
    private $creationDate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\PositiveOrZero
     */
    private $voteCounter = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="articles")
     */
    private $category;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastModified;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="modifiedArticles")
     */
    private $LastModifiedBy;

    public function __construct()
    {
        $this->setCreationDate(new DateTime());
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreationDate(): DateTime
    {
        return $this->creationDate;
    }

    public function setCreationDate(DateTime $creationDate): self
    {
        $this->creationDate = $creationDate;
        return $this;
    }

    public function getVoteCounter(): ?int
    {
        return $this->voteCounter;
    }

    public function setVoteCounter(?int $voteCounter): self
    {
        $this->voteCounter = $voteCounter <= 0 ? 0 : $voteCounter;

        return $this;
    }

    public function upVote()
    {
        $newCounter = $this->getVoteCounter();
        $this->setVoteCounter(++$newCounter);
    }

    public function downVote()
    {
        $newCounter = $this->getVoteCounter();
        $this->setVoteCounter(--$newCounter);
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getLastModified(): ?\DateTimeInterface
    {
        return $this->lastModified;
    }

    public function setLastModified(?\DateTimeInterface $lastModified): self
    {
        $this->lastModified = $lastModified;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLastModifiedBy(): ?User
    {
        return $this->LastModifiedBy;
    }

    public function setLastModifiedBy(?User $LastModifiedBy): self
    {
        $this->LastModifiedBy = $LastModifiedBy;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use FOS\CKEditorBundle\Form\Type\CKEditorType;


class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre'
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'label' => 'Catégorie'
            ])
            ->add('content', CKEditorType::class, [
                'label' => 'Contenu'
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Publier mon article'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Faker\Factory;
use App\Entity\Article;
use App\Form\ArticleType;

class ArticleController extends AbstractController
{
    private string $title = 'Tous les articles';

    /**
     * @param ArticleRepository $repo
     * @param Request $request
     * @return Response
     */
    #[Route("/article", name: "article")]
    public function index(ArticleRepository $repo, Request $request): Response
    {
        $getParam = $request->query->get('q');
        $articles = is_null($getParam) ?
            $repo->findBy([], ['creationDate' => 'DESC']) :
            $repo->findTitleOrContentWith($getParam);

        return $this->render('article/index.html.twig', [
            'title' => $this->title,
            'q' => $getParam,
            'articles' => $articles
        ]);
    }

    /**
     * @return Response
     */
    #[Route("/article/twig", name: "twig")]
    public function twig(): Response
    {
        // Create array of random numbers
        $arrayNumbers = range(1, 100);
        shuffle($arrayNumbers);
        $arrayNumbers = array_slice($arrayNumbers, 0, 10);

        // Create array of strings
        $arrayString = ['hello', 'bonjour', 'hallo', 'hoi'];
        shuffle($arrayString);

        // Create random date
        $date = $this->randomDate('2021-01-01', '2021-12-31');

        return $this->render('article/array.html.twig', [
            'title' => $this->title,
            'arrayNumbers' => $arrayNumbers,
            'arrayString' => $arrayString,
            'date' => $date
        ]);
    }

    /**
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return RedirectResponse|Response
     */
    #[Route('/article/new', name: 'create')]
    public function create(Request $request, EntityManagerInterface $em): RedirectResponse|Response
    {
        $article = new Article();

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $article->setUser($this->getUser());

            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('article_detail', ['id' => $article->getId()]);
        }

        return $this->renderForm('article/new.html.twig', [
            'form' => $form
        ]);
    }

    /**
     * @param Request $request
     * @param Article $article
     * @param EntityManagerInterface $em
     * @return Response
     */
    #[Route('/article/update/{id}', name: 'update_article')]
    public function update(Request $request, Article $article, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $article->setLastModified(new \DateTime());
            $article->setLastModifiedBy($this->getUser());

            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('article_detail', ['id' => $article->getId()]);
        }

        return $this->renderForm('article/update.html.twig', [
            'form' => $form,
            'article' => $article
        ]);
    }

    /**
     * @param int $id
     * @param ArticleRepository $repo
     * @return Response
     */
    #[Route("/article/{id}", name: "article_detail")]
    public function show(int $id, ArticleRepository $repo): Response
    {
        if (!is_numeric($id)) {
            return $this->render('article/404.html.twig');
        }

        $article = $repo->find($id);

        if (!$article) {
            return $this->render('article/404.html.twig');
        }

        return $this->render('article/article.html.twig', [
            'article' => $article
        ]);
    }

    /**
     * @param string $year
     * @param ArticleRepository $repo
     * @return Response
     */
    #[Route("/article/year/{year}", name: "year_articles")]
    public function showArticlesByYear(string $year, ArticleRepository $repo): Response
    {
        $articles = $repo->getArticlesByYear($year);

        if (!$articles) {
            return $this->render('article/404.html.twig');
        }

        return $this->render('article/index.html.twig', [
            'title' => "Tous les articles publiés en $year",
            'articles' => $articles
        ]);
    }

    /**
     * @param Article $article
     * @param EntityManagerInterface $em
     * @return JsonResponse
     */
    #[Route("/article/{id}/up", name: "up_vote")]
    public function upVote(Article $article, EntityManagerInterface $em): JsonResponse
    {
        $article->upVote();

        $em->flush();

        return new JsonResponse($article->getVoteCounter());
    }

    /**
     * @param Article $article
     * @param EntityManagerInterface $em
     * @return JsonResponse
     */
    #[Route("/article/{id}/down", name: "down_vote")]
    public function downVote(Article $article, EntityManagerInterface $em): JsonResponse
    {
        $article->downVote();

        $em->flush();

        return new JsonResponse($article->getVoteCounter());
    }

    /**
     * @param $startDate
     * @param $endDate
     * @return string
     */
    public function randomDate($startDate, $endDate): string
    {
        $min = strtotime($startDate);
        $max = strtotime($endDate);

        $date = rand($min, $max);

        return date('d/m/Y', $date);
    }
}

templates/article/404.html.twig
{% extends 'base.html.twig' %}

{% block title %} Article non trouvé {% endblock %}

{% block body %}

<div class="body-wrapper">
    <h1>Article non trouvé</h1>
    <p>Oups ! Cet article n'existe pas !</p>
    <a href="{{ path('article') }}">Revenir à la liste des articles</a>
</div>

{% endblock %}

templates/article/array.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

<div class="body-wrapper">
    <h1>{{ title }}</h1>

    <h2>Tableau de nombres pairs et impairs</h2>
    <p> Le tableau : {{ arrayNumbers|join(", ") }}</p>
    
    <h3>Chiffres pairs</h3>
    <ul>
    {% for number in arrayNumbers|filter(number => number is even) %}
        <li>{{ number }}</li>
    {% endfor %}
    </ul>
    <h3>Chiffres impairs</h3>
    <ul>
    {% for number in arrayNumbers|filter(number => number is odd) %}
        <li>{{ number }}</li>
    {% endfor %}
    </ul>

    <h3>Plus grand nombre : {{ max(arrayNumbers) }}</h3>

    <h3>Nombre aléatoire : {{ random(arrayNumbers) }}
    

    <h2>Tableau string</h2>

    <h3>Premier élément</h3>
    <p>{{ arrayString|first }}</p>

    <h3>Première lettre en majuscile</h3>
    <ul>
    {% for string in arrayString %}
        <li>{{ string|capitalize }}</li>
    {% endfor %}
    </ul>

    <h3>Chaîne aléatoire : {{ random(arrayString)|capitalize }}

    <h2>Date</h2>
    {% if date != date() %}
        <p class="not_today">Ce n'est pas la date du jour : {{ date }}</p>
    {% else %}
        <p class="today">C'est aujourd'hui : {{ date }}</p>
    {% endif %}

    
</div>
{% endblock %}

templates/article/article.html.twig
{% extends 'base.html.twig' %}

{% block navbarAdmin %}
    {{ parent() }}
    {% if is_granted('ROLE_USER') %}
        <li>
            <a class="admin-navbar-item item-update" href=" {{ path('update_article', { id: article.id }) }}">
                <i title="Modifier un article" class="fas fa-pencil-alt"></i>
            </a>
        </li>
    {% endif %}
{% endblock %}

{% block title %}{{ article.title }}{% endblock %}

{% block body %}
    <div class="body-wrapper">
        <h1>[{{ article.category.name }}] {{ article.title }}</h1>
        {# Filtre |raw pour afficher html généré par CKEditor ! #}
        <p>{{ article.content|raw }}</p>
        <p>Article publié le {{ article.creationDate|date('d/m/Y') }}
            par {{ article.user.firstName ~ ' ' ~ article.user.lastName }}</p>
        {% if article.lastModified is not null %}
            <p>Article modifié le {{ article.lastModified|date('d/m/Y') }} à {{ article.lastModified|date('H:i') }}
                par {{ article.lastModifiedBy.firstName ~ ' ' ~ article.lastModifiedBy.lastName }}</p>
        {% endif %}
        <div class="vote">
            <p>Que pensez-vous de cet article ?</p>
            <span id="up" data-id="{{ article.id }}" class="vote-up up">+</span>
            <span id="vote-number" class="vote-number">{{ article.voteCounter }}</span>
            <span id="down" data-id="{{ article.id }}" class="vote-down down">-</span>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script async="true" src="{{ asset('js/vote.js') }}"></script>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block navbarAdmin %}
    {{ parent() }}
    {% if is_granted('ROLE_USER') %}
        <li class="item-container">
            <a class="admin-navbar-item item-create" href=" {{ path('create') }}">
                <i title="Créer un nouvel article" class="fas fa-plus"></i>
            </a>
        </li>
    {% endif %}
{% endblock %}

{% block body %}

    <div class="body-wrapper">
        <h1>{{ title }} {% if q is not null %} avec "{{ q }}" {% endif %}</h1>
        <p>Il y a {{ articles|length }} résultat{% if articles|length > 1 %}s{% endif %} :</p>
        {% if articles != false %}
            {% for article in articles %}
                <section class="article-preview">
                    <h3>
                        <a {{ article.creationDate|date('U') > "-7 days"|date('U') ? "class=\"new-article\" " : "" }}href="{{ path("article_detail", { id : article.id }) }}">{{ article.title }}</a>
                    </h3>
                    <p class="creation-date">Publié le {{ article.creationDate|date('d/m/Y') }} - Catégorie
                        : {{ article.category.name }}</p>
                    {% if article.content|length > 300 %}
                        <p>{{ article.content|slice(0,300)|raw ~ '...' }}</p>
                        <p><a href="{{ path("article_detail", { id : article.id }) }}">Lire
                                l'article "{{ article.title }}"</a></p>
                    {% else %}
                        <p>{{ article.content|raw }}</p>
                    {% endif %}

                </section>
            {% endfor %}
        {% else %}
            <p>Aucun article ne correspond à votre recherche "{{ q }}".</p>
            <a href="{{ path('article') }}">Revenir à la liste des articles</a>
        {% endif %}
    </div>

{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un article{% endblock %}

{% block body %}

<div class="body-wrapper">
<h1>Ajouter un article</h1>

    {{ form(form) }}
</div>
{% endblock %}

templates/article/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un article{% endblock %}



{% block body %}

    <div class="body-wrapper">
        <h1>Modifier "{{ article.title }}"</h1>

        {{ form(form) }}
    </div>
{% endblock %}